### PR TITLE
added project name and output dirs

### PR DESCRIPTION
**Pull request by donhinton**
set newer cmake version (to support project version), added project + version, and setup output directory paths.

I'll add rpath stuff at some point, but since you don't have any libraries yet, it isn't an issue.  However, you may want to do it automatically for your compiler.  Do you use clang or just gcc?   Also, which OS's do you plan to support?

### CODE REVIEW

**Comment by venediktov** [comment]
I'd like to support gcc and clang and maybe other compilers windows ?

**Comment by donhinton** [comment]
yes, you can pass build type when you run cmake.  you might want to set some other variables as well, but cmake takes care of a lot.  This is mainly a windows thing.  Run cmake like this:

cmake -DCMAKE_BUILD_TYPE=DEBUG ../CRUD -GNinja

**Comment by donhinton** [comment]
btw, here's part of a script i use to build clang.  it gives an example of several useful variables...

cmake -DCMAKE_C_COMPILER=${CLANG_GCC}/bin/gcc \
      -DCMAKE_CXX_COMPILER=${CLANG_GCC}/bin/g++ \
      -DGCC_INSTALL_PREFIX=${CLANG_GCC} \
      -DCMAKE_CXX_LINK_FLAGS="-L${CLANG_GCC}/lib64 -Wl,-rpath,${CLANG_GCC}/lib64" \
      -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
      -DLLVM_ENABLE_ASSERTIONS=ON \
      -DCMAKE_BUILD_TYPE="Release" \
      -DLLVM_TARGETS_TO_BUILD="X86" \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      ../llvm \
      -GNinja || die "cmake failed"

**Comment by venediktov** [comment]
-GNinja fails for me,  do I have to  install Ninja ? If so I have not done yet , so using "Unix Makefiles"
I was building CRUD like this
 ~/GIT/CRUD> mkdir build 
~/GIT/CRUD> cd build
~/GIT/CRUD/build> cmake -G "Unix Makefiles" ../

Thanks for DEBUG info , I can build it in either DEBUG or RELEASE now

**Comment by donhinton** [comment]
yes, if you want to use it.  on linux, cmake defaults to gnu make.

**Pull request merged**
