### PR TITLE
initial cmake changes

### PR DESCRIPTION
**Pull request by donhinton**
Initial cmake setup, but fails to compile -- something about flush.

### CODE REVIEW

**Comment by venediktov** [comment]
Hi Don, I just fixed compilation of reply.cpp and reply.hpp , it compiles , but linking still an issue , I think 
it needs -lpthread in your cmake ?

**Comment by donhinton** [comment]
rpath can be a security issue, so I wouldn't add it to the CMakeLists.txt files, but you could pass it to cmake.  LD_LIBRARY_PATH is probably safer.  That said, I do add it when I build gcc or clang, but that code isn't run by web servers.

**Comment by venediktov** [comment]
I had to run following commands to merge succesfully 
git clone git@github.com:venediktov/CRUD.git
git checkout cmake
git pull
git checkout master
git merge cmake
git push

**Comment by donhinton** [comment]
you can also do it in the gui if you want.

**Comment by venediktov** [comment]
Don, I have UI installed on my Mac but for developement I use Linux, so will install Git UI on my Linux too !

**Comment by donhinton** [comment]
I'm talking about the github web pagei.   Scroll down the conversation tab on the pull request page, and you'll see a "merge" button.  How that it's been merged, all you'll see is the delete branch button.

**Comment by venediktov** [comment]
Oh, I see now. 
Question  : if I am working on a small feature, should I just creat a local branch from the master, then
merge it locally and then push into remote repo ?

**Comment by donhinton** [comment]
I like to work in master and branch once i'm ready to commit.  Once in a branch, i stay there until it's ready to merge to master.  It's not uncommon for me to have multiple branches active at the same time.  

But don't think of it as a hard and fast rule.

**Pull request merged**
